apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-dep-pod
  template:
    metadata:
      labels:
        app: keycloak-dep-pod
    spec:
      containers:
        - name: keycloak-container
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          env:
          - name: KC_BOOTSTRAP_ADMIN_USERNAME
            value: admin
          - name: KC_BOOTSTRAP_ADMIN_PASSWORD
            value: admin
          ports:
          - containerPort: 8080