version: '3.8'
services:

  mysql:
    image: galarconm/tfm:mysql-db-v3
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
    volumes:
      - mysql_data:/var/lib/mysql

  guacd:
    image: guacamole/guacd:1.5.5
    container_name: guacd-proxy

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole-container
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_password
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
    depends_on:
      - guacd
      - mysql
  spyder:
    image: galarconm/tfm:spyder-rdp-v1
    container_name: spyder
    ports:
      - "5901:5901"

  geany:
    image: galarconm/tfm:geany-rdp-v2
    container_name: geany
    ports:
      - "5902:5902"

  jupyter:
    image: galarconm/tfm:jupyter-rdp-v1
    container_name: jupyter
    ports:
      - "5903:5903"

  frontend-jenkins:
    image: galarconm/tfm:frontend-jenkins-v3
    container_name: frontend-jenkins
    ports:
      - "8090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  mysql_data:
    driver: local
  jenkins_home:
    driver: local
