apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-pv
  annotations:
    description: "Persistent volume for home"
spec:
  storageClassName: nfs-subdir
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany #
  nfs:
    path: /var/nfs_share/home
    server: 192.168.1.17
    readOnly: false

