apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  annotations:
    description: "Persistent volume for Jenkins"
spec:
  storageClassName: nfs-subdir
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.17
    path: /var/nfs_share/jenkins
    readOnly: false
