apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  annotations:
    description: "Persistent volume for PostgreSQL"
spec:
  storageClassName: nfs-subdir
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.17
    path: /var/nfs_share/postgres
    readOnly: false
