# Usar una imagen base oficial de Ubuntu WEB OK
FROM python:3.9-slim

# Evitar advertencias cambiando a no interactivo durante el proceso de construcción
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    xvfb \
    xrdp \
    xfce4 \
    dbus-x11 \
    geany \
    firefox-esr \
    git \
    xterm \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
   
# Configurar xfce4 como el entorno de escritorio para xrdp
RUN echo xfce4-session > /root/.xsession

# Test github actions again22345

# Exponer puertos para RDP (3389)
EXPOSE 3389

# Copiar script de inicio
COPY start_rdp.sh /usr/local/bin/start_rdp.sh
RUN chmod +x /usr/local/bin/start_rdp.sh

# Comando para iniciar xrdp y el entorno de escritorio xfce4
CMD service xrdp start && /usr/local/bin/start_rdp.sh
