FROM jenkins/jenkins:2.494

#ENV JENKINS_USER admin
#ENV JENKINS_PASS admin


#create jenkins admin user
RUN echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('admin', 'admin')" > /usr/share/jenkins/ref/init.groovy.d/basic-security.groovy

#create student user
#RUN echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('student', 'student')" > /usr/share/jenkins/ref/init.groovy.d/student-security.groovy


# Skip initial setup
#ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false


USER root


RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    nano \
    bc \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Clone the ACTaaS repository from GitHub to the desired directory
RUN git clone https://github.com/grycap/ACTaaS /var/tmp/education/ACTaaS

# Set permissions for the unittest scripts directory
RUN chmod -R 0777 /var/tmp/education/ACTaaS/practices/P1/Face/unittests
# Correct the permissions for the unittest directory to 0755
RUN chmod 0755 /var/tmp/education/ACTaaS/practices/P1/Face/unittests

COPY plugin.txt /usr/share/jenkins/ref/plugin.txt

RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugin.txt

RUN mv /var/tmp/education/ACTaaS/scripts_jenkins/jenkins-cli.jar /var/tmp/education/ACTaaS/

WORKDIR /var/tmp/education/ACTaaS

EXPOSE 8080

# Run the Docker container with a named volume
#docker run -d -p 8080:8080 --name cont1 front:jenkins
