FROM jenkins/jenkins:2.464 

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    nano \
    bc \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY plugin.txt /usr/share/jenkins/ref/plugin.txt

RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugin.txt

USER jenkins

EXPOSE 8090

# Run the Docker container with a named volume
#docker run -d -v jenkins_home:/var/jenkins_home -p 8081:8081 --name front:jenkins

