# Dockerfile para Keycloak
FROM keycloak/keycloak:26.0

# Establecer las variables de entorno
ENV KC_BOOTSTRAP_ADMIN_USERNAME=admin \
    KC_BOOTSTRAP_ADMIN_PASSWORD=admin

# Exponer los puertos
EXPOSE 8081

# Iniciar el servidor Keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]