# Dockerfile para Spyder con soporte RDP
FROM python:3.9-slim

# Instalar dependencias
RUN apt-get update && \
    apt-get install -y \
    python3-pyqt5 \
    python3-dev \
    python3-pyqt5.qtwebkit \
    build-essential \
    xvfb \
    xrdp \
    xfce4 \
    dbus-x11 \
    firefox-esr \
    git \
    xterm \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
         
# Instalar Spyder
RUN pip install spyder

# Configurar xfce4 como el entorno de escritorio para xrdp
RUN echo xfce4-session > /root/.xsession

# Crear una cuenta de usuario
RUN useradd -m myuser && yes mypassword | passwd myuser

# Exponer puertos para RDP (3389)
EXPOSE 3389

# Copiar script de inicio
COPY start_rdp.sh /usr/local/bin/start_rdp.sh
RUN chmod +x /usr/local/bin/start_rdp.sh

# Copiar script add_users.sh
COPY add_users.sh /usr/local/bin/add_users.sh
RUN chmod +x /usr/local/bin/add_users.sh

# Comando para iniciar xrdp y Spyder
CMD service xrdp start && /usr/local/bin/start_rdp.sh