#keycloak

FROM jboss/keycloak:latest

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    nano \
    bc \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 8181