FROM jenkins/jenkins:2.494

# Crear usuario administrador de Jenkins
RUN echo "jenkins.model.Jenkins.instance.securityRealm.createAccount('admin', 'admin')" > /usr/share/jenkins/ref/init.groovy.d/basic-security.groovy

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    nano \
    bc \
    git \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Clonar el repositorio ACTaaS desde GitHub al directorio deseado
RUN git clone https://github.com/grycap/ACTaaS /var/tmp/education/ACTaaS

# Establecer permisos para el directorio de scripts de pruebas unitarias
RUN chmod -R 0777 /var/tmp/education/ACTaaS/practices/P1/Face/unittests
# Corregir los permisos del directorio de pruebas unitarias a 0755
RUN chmod 0755 /var/tmp/education/ACTaaS/practices/P1/Face/unittests

COPY plugin.txt /usr/share/jenkins/ref/plugin.txt

RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugin.txt

RUN mv /var/tmp/education/ACTaaS/scripts_jenkins/jenkins-cli.jar /var/tmp/education/ACTaaS/

WORKDIR /var/tmp/education/ACTaaS

EXPOSE 8080