apiVersion: apps/v1
kind: Deployment
metadata:
  name: geany-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geany-dep-pod
  template:
    metadata:
      labels:
        app: geany-dep-pod
    spec:
      containers:
      - name: geany
        image: galarconm/tfm:geany-rdp-v2
        ports:
        - containerPort: 3389
        securityContext:
          runAsUser: 0  # Run container as root
        volumeMounts:
        - name: geany-data
          # Path to the folder where the data will be stored for all users
          mountPath: /home/userdata 
      volumes:
      - name: geany-data
        persistentVolumeClaim:
          claimName: home-pvc

