apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole-dep-pod
  template:
    metadata:
      labels:
        app: guacamole-dep-pod
    spec:
      containers:
        - name: guacamole-dep
          image: guacamole/guacamole:1.5.5
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_DATABASE
              value: guacamole_db
            - name: MYSQL_USER
              value: guacamole_user
            - name: MYSQL_PASSWORD
              value: guacamole_password
            - name: GUACD_HOSTNAME
              value: guacd-svc
            - name: MYSQL_HOSTNAME
              value: mysql-svc
            - name: OPENID_CLIENT_ID
              value: guacamole
            - name: OPENID_REDIRECT_URI
              value: http://192.168.49.2:30000/guacamole
            - name: OPENID_ISSUER
              value: http://192.168.49.2:31001/realms/guacamole
            - name: OPENID_AUTHORIZATION_ENDPOINT
              value: http://192.168.49.2:31001/realms/guacamole/protocol/openid-connect/auth
            - name: OPENID_JWKS_ENDPOINT
              value: http://192.168.49.2:31001/realms/guacamole/protocol/openid-connect/certs
            - name: OPENID_TOKEN_ENDPOINT
              value: http://192.168.49.2:31001/realms/guacamole/protocol/openid-connect/token
            - name: OPENID_USERINFO_ENDPOINT
              value: http://192.168.49.2:31001/realms/guacamole/protocol/openid-connect/userinfo
            - name: OPENID_LOGOUT_ENDPOINT
              value: http://192.168.49.2:31001/realms/guacamole/protocol/openid-connect/logout
            - name: extension-priority
              value: "*, openid"
            - name: OPENID_CLAIM_USERNAME
              value: preferred_username
            - name: OPENID_CLAIM_GROUPS
              value: groups
