apiVersion: apps/v1
kind: Deployment
metadata:
  name: spyder-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spyder-dep-pod
  template:
    metadata:
      labels:
        app: spyder-dep-pod
    spec:
      containers:
      - name: spyder
        image: galarconm/tfm:spyder-rdp-v1
        ports:
        - containerPort: 3389
        volumeMounts:
        - name: spyder-data
          mountPath: /home
      volumes:
      - name: spyder-data
        persistentVolumeClaim:
          claimName: home-pvc
